# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deno setup
        uses: denoland/setup-deno@v1
        with:
          node-version: v1.x

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 10
          platform: x64

      - name: Cmake setup
        uses: lukka/get-cmake@latest

      - name: Ninja setup
        uses: seanmiddleditch/gha-setup-ninja@master
      
      - name: Build and run native
        run: bash ${GITHUB_WORKSPACE}/scripts/build.sh
